# Generated by Django 5.1.1 on 2024-09-18 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
        ('Booking', '0002_delete_paymentmethods'),
        ('Event', '0001_initial'),
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_seats_booked', models.IntegerField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.event')),
                ('paid_using', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payment.paymentmethods')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.user')),
            ],
        ),
    ]
