# Generated by Django 5.1.1 on 2024-10-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmedia',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='eventmedia',
            name='size',
        ),
        migrations.AddField(
            model_name='event',
            name='genre',
            field=models.ManyToManyField(related_name='events', to='Event.genre'),
        ),
        migrations.AddField(
            model_name='eventmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='type',
            field=models.CharField(choices=[('BANNER', 'banner'), ('DETAIL', 'detail')], default='BANNER', max_length=100),
        ),
        migrations.DeleteModel(
            name='EventGenre',
        ),
    ]
